-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- User-filed reports against a mosaic artwork submission ("post"), a
-- mosaic_submission_comments row ("comment"), or a profiles row ("account").
-- One generic table rather than three near-identical ones, since every
-- report needs the same shape: who filed it, what it points at, why, and
-- its moderation status. target_id is text so it can hold either a
-- mosaic_submissions/mosaic_submission_comments bigint id or a profiles uuid.

create table if not exists public.reports (
  id            bigint generated by default as identity primary key,
  reporter_id   uuid not null references auth.users(id) on delete cascade,
  target_type   text not null check (target_type in ('submission', 'comment', 'profile')),
  target_id     text not null,
  reason        text not null check (reason in ('spam', 'harassment', 'hate_speech', 'nudity', 'misinformation', 'other')),
  details       text,
  status        text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  created_at    timestamptz not null default now(),
  constraint reports_details_len check (details is null or char_length(details) <= 1000),
  -- One report per person per target — resubmitting just means "I still mean it", not a new row.
  unique (reporter_id, target_type, target_id)
);

create index if not exists reports_target_idx on public.reports (target_type, target_id);
create index if not exists reports_status_idx on public.reports (status, created_at);

alter table public.reports enable row level security;

-- Only moderators can read the queue — a reporter doesn't get to see who
-- else reported what, and a reported user should never see reports naming them.
drop policy if exists "Admins can view all reports" on public.reports;
create policy "Admins can view all reports"
  on public.reports for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

drop policy if exists "Signed-in users can file reports" on public.reports;
create policy "Signed-in users can file reports"
  on public.reports for insert
  with check (auth.uid() = reporter_id);

drop policy if exists "Admins can update report status" on public.reports;
create policy "Admins can update report status"
  on public.reports for update
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

-- RLS policies only take effect once the role has table-level privileges too —
-- see supabase_profiles.sql for the same gotcha with anon/select.
grant select, update on public.reports to authenticated;
grant insert on public.reports to authenticated;
