-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- Run AFTER supabase_notifications.sql (this adds a column to that table and
-- a trigger on it) and AFTER supabase_site_settings.sql (the Edge Function
-- URL is a site option).
--
-- Web push delivery for the in-app notification feed (2026-09-11). The feed
-- itself already exists: triggers in supabase_notifications.sql insert a row
-- when someone likes, comments, replies or follows, and js/notifications.js
-- shows it live over Realtime. Realtime only reaches a page that is OPEN,
-- so nothing arrived once the app was closed — that is what this file fixes.
--
-- Shape of the whole thing:
--   notifications INSERT
--     → trigger below asks pg_net to POST {id} at the Edge Function
--     → supabase/functions/push/index.ts calls claim_push(id) with the
--       service role, gets the recipient's subscriptions, and sends one
--       encrypted Web Push message per device
--     → sw.js (site root) shows the notification.
--
-- WHY THE ENDPOINT NEEDS NO SECRET: claim_push() stamps notifications.pushed_at
-- inside the same statement that reads the row, so a given notification is
-- delivered at most once no matter how often the endpoint is called, and it
-- can only ever be delivered to the recipient already recorded on the row.
-- A stranger POSTing random ids therefore achieves nothing but a wasted
-- round trip. That is what lets the Edge Function be deployed with
-- --no-verify-jwt and keeps every secret (the VAPID private key, the service
-- role key) inside Supabase rather than in this repository (CLAUDE.md §3).

-- ── 1. pg_net: the database's outbound HTTP client ───────────────────────
-- Fire-and-forget — http_post() queues the request and returns, so the
-- insert that triggered it is never held up (and never fails) because of it.
-- No `with schema` clause: Supabase installs this either as `net` or under
-- `extensions` depending on how it was enabled, and pinning the wrong one
-- fails outright. The dispatcher below therefore calls http_post()
-- unqualified with both schemas on its (fixed) search_path.
-- Already enabled? This is a no-op. Not permitted from the SQL editor on
-- your plan? Enable "pg_net" under Database → Extensions instead.
create extension if not exists pg_net;

-- ── 2. push_subscriptions ────────────────────────────────────────────────
-- One row per browser/app install that has granted permission. endpoint is
-- the push service's URL for that device and is the natural key: the same
-- browser re-subscribing updates its row instead of leaving a dead endpoint
-- behind for the sender to keep retrying (js/push.js upserts on it).
create table if not exists public.push_subscriptions (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  endpoint     text not null unique,
  p256dh       text not null,
  auth         text not null,
  user_agent   text,
  -- Which language this device asked for, so the message text matches the
  -- pages that user actually reads (there is no per-account language).
  lang         text not null default 'ko' check (lang in ('ko', 'en')),
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.push_subscriptions
  add column if not exists lang text not null default 'ko';

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

-- A user manages only their own devices. Nobody can read anyone else's
-- endpoint — an endpoint is a capability: whoever holds it can send that
-- device a notification.
drop policy if exists "Users read their own push subscriptions" on public.push_subscriptions;
create policy "Users read their own push subscriptions"
  on public.push_subscriptions for select
  using (user_id = auth.uid());

drop policy if exists "Users delete their own push subscriptions" on public.push_subscriptions;
create policy "Users delete their own push subscriptions"
  on public.push_subscriptions for delete
  using (user_id = auth.uid());

-- Registering goes through save_push_subscription() below, never a direct
-- insert/update — so those two are not granted at all. Dropped here in case
-- an earlier run of this file created them.
drop policy if exists "Users add their own push subscriptions" on public.push_subscriptions;
drop policy if exists "Users update their own push subscriptions" on public.push_subscriptions;

grant select, delete on public.push_subscriptions to authenticated;
-- Never anon: an unauthenticated caller has no device of its own to register.

-- ── 2b. save_push_subscription: "this device is mine now" ────────────────
-- A push endpoint belongs to a BROWSER, not to an account, so two accounts
-- sharing one phone produce the same endpoint. A plain upsert breaks there:
-- the row still belongs to whoever signed in first, and the update policy
-- (rightly) refuses to let the second account touch it — the newcomer would
-- silently get no notifications. This hands the endpoint over instead, which
-- matches what actually happened: the device is now signed in as someone
-- else, and the previous owner's session on it is gone.
create or replace function public.save_push_subscription(
  p_endpoint text,
  p_p256dh   text,
  p_auth     text,
  p_lang     text default 'ko',
  p_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
begin
  if auth.uid() is null then
    raise exception 'sign-in required';
  end if;
  if coalesce(p_endpoint, '') = '' or coalesce(p_p256dh, '') = '' or coalesce(p_auth, '') = '' then
    raise exception 'endpoint, p256dh and auth are required';
  end if;

  delete from public.push_subscriptions where endpoint = p_endpoint;

  insert into public.push_subscriptions (user_id, endpoint, p256dh, auth, lang, user_agent, last_seen_at)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth,
          case when p_lang = 'en' then 'en' else 'ko' end,
          left(p_user_agent, 300), now());
end;
$fn$;

revoke execute on function public.save_push_subscription(text, text, text, text, text) from public, anon;
grant execute on function public.save_push_subscription(text, text, text, text, text) to authenticated;

-- ── 3. notifications.pushed_at ───────────────────────────────────────────
-- Null until delivery has been claimed. Also the answer to "did this one go
-- out?" when a user says they never got it.
alter table public.notifications
  add column if not exists pushed_at timestamptz;

-- ── 4. claim_push: the Edge Function's single call ───────────────────────
-- Claims the row and returns everything needed to build the message. The
-- claim and the read are one statement, so two concurrent calls cannot both
-- win: the loser gets null and sends nothing.
--
-- Returns null when the id does not exist, was already pushed, or the
-- recipient has no devices registered.
create or replace function public.claim_push(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_row   public.notifications;
  v_actor text;
  v_subs  jsonb;
begin
  update public.notifications
     set pushed_at = now()
   where id = p_id and pushed_at is null
  returning * into v_row;

  if v_row.id is null then
    return null;                                  -- unknown id, or already sent
  end if;

  select coalesce(username, name) into v_actor
  from public.profiles where id = v_row.actor_id;

  select coalesce(jsonb_agg(jsonb_build_object(
           'endpoint', s.endpoint, 'p256dh', s.p256dh, 'auth', s.auth, 'lang', s.lang)), '[]'::jsonb)
    into v_subs
  from public.push_subscriptions s
  where s.user_id = v_row.recipient_id;

  if jsonb_array_length(v_subs) = 0 then
    return null;                                  -- nothing registered
  end if;

  return jsonb_build_object(
    'type',          v_row.type,
    'preview',       v_row.preview,
    'actor',         v_actor,
    'submission_id', v_row.submission_id,
    'subscriptions', v_subs
  );
end;
$fn$;

-- Service role only. The function hands out push endpoints, which are
-- capabilities — no browser-held key may call it.
revoke execute on function public.claim_push(bigint) from public, anon, authenticated;
grant execute on function public.claim_push(bigint) to service_role;

-- ── 5. drop_push_subscription: retire an endpoint the push service rejected
-- A 404/410 from the push service means the browser is gone for good.
create or replace function public.drop_push_subscription(p_endpoint text)
returns void
language sql
security definer
set search_path = public
as $fn$
  delete from public.push_subscriptions where endpoint = p_endpoint;
$fn$;

revoke execute on function public.drop_push_subscription(text) from public, anon, authenticated;
grant execute on function public.drop_push_subscription(text) to service_role;

-- ── 6. the trigger that asks the Edge Function to deliver ────────────────
-- Site option `pushEndpoint` holds the function URL (empty = delivery off,
-- which is the state until it is filled in on /admin). Wrapped so that a
-- failure here can never fail the INSERT that produced the notification —
-- an undelivered push is an annoyance, a lost notification row is a bug.
create or replace function public.dispatch_push_notification()
returns trigger
language plpgsql
security definer
set search_path = public, net, extensions
as $fn$
declare
  v_url text;
begin
  select nullif(trim(settings->>'pushEndpoint'), '') into v_url
  from public.site_settings where id = true;

  if v_url is null then
    return new;
  end if;

  begin
    -- Unqualified on purpose — see the pg_net note at the top of this file.
    -- search_path is fixed in this function's definition, so this is not the
    -- usual security-definer search_path hazard.
    perform http_post(
      url     := v_url,
      body    := jsonb_build_object('id', new.id),
      headers := jsonb_build_object('Content-Type', 'application/json'),
      timeout_milliseconds := 4000
    );
  exception when others then
    raise warning 'push dispatch failed for notification %: %', new.id, sqlerrm;
  end;

  return new;
end;
$fn$;

drop trigger if exists trg_dispatch_push_notification on public.notifications;
create trigger trg_dispatch_push_notification
  after insert on public.notifications
  for each row execute function public.dispatch_push_notification();
