-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- In-app notification feed (the top-nav bell in js/notifications.js): tells a
-- user when someone likes their artwork, comments on it, replies to one of
-- their comments, or follows them.
--
-- Rows are written ONLY by the security-definer triggers at the bottom of
-- this file — never by the browser. The client holds just the publishable
-- key under RLS, so it can't be trusted to insert rows addressed to another
-- user; and a trigger fires for every insert into the source table no matter
-- which code path caused it (lightbox like/comment, pool matching, etc.).
-- Same tool the rest of the schema already reaches for cross-row work — see
-- check_mosaic_comment_parent() in supabase_mosaic_comments.sql.

create table if not exists public.notifications (
  id            bigint generated by default as identity primary key,
  recipient_id  uuid not null references auth.users(id) on delete cascade,
  actor_id      uuid references auth.users(id) on delete cascade,
  type          text not null check (type in (
                  'submission_like', 'submission_comment', 'submission_reply', 'follow'
                )),
  submission_id bigint references public.mosaic_submissions(id) on delete cascade,
  comment_id    bigint references public.mosaic_submission_comments(id) on delete cascade,
  -- Denormalised bit of context for the feed row: the artwork's title for a
  -- like, the first ~140 chars of the comment body for a comment/reply.
  preview       text,
  created_at    timestamptz not null default now(),
  read_at       timestamptz
);

create index if not exists notifications_recipient_idx
  on public.notifications (recipient_id, created_at desc);
-- Unread-count query (bell badge) only ever touches the null-read_at rows.
create index if not exists notifications_recipient_unread_idx
  on public.notifications (recipient_id) where read_at is null;

-- One like-notification per (recipient, actor, artwork) and one
-- follow-notification per (recipient, actor) — a like-unlike-relike or a
-- follow-unfollow-refollow bumps the existing row (see the ON CONFLICT
-- clauses in the trigger functions) instead of stacking duplicates.
create unique index if not exists notifications_like_uniq
  on public.notifications (recipient_id, actor_id, submission_id)
  where type = 'submission_like';
create unique index if not exists notifications_follow_uniq
  on public.notifications (recipient_id, actor_id)
  where type = 'follow';

alter table public.notifications enable row level security;

drop policy if exists "Users can read their own notifications" on public.notifications;
create policy "Users can read their own notifications"
  on public.notifications for select
  using (recipient_id = auth.uid());

-- Only ever used by the client to stamp read_at; scoped to the owner's own
-- rows either way.
drop policy if exists "Users can update their own notifications" on public.notifications;
create policy "Users can update their own notifications"
  on public.notifications for update
  using (recipient_id = auth.uid())
  with check (recipient_id = auth.uid());

drop policy if exists "Users can delete their own notifications" on public.notifications;
create policy "Users can delete their own notifications"
  on public.notifications for delete
  using (recipient_id = auth.uid());

-- Deliberately NO insert policy and NO insert grant — inserts come only from
-- the security-definer triggers below, which run as the table owner and so
-- bypass RLS.
grant select, update, delete on public.notifications to authenticated;

-- ── like on your artwork ────────────────────────────────────────────────
create or replace function public.notify_submission_like()
returns trigger as $$
declare
  v_author uuid;
  v_title  text;
begin
  select author_id, art_title into v_author, v_title
  from public.mosaic_submissions where id = new.submission_id;

  if v_author is null or v_author = new.user_id then
    return new; -- own artwork, or artwork vanished mid-transaction
  end if;

  insert into public.notifications (recipient_id, actor_id, type, submission_id, preview)
  values (v_author, new.user_id, 'submission_like', new.submission_id, v_title)
  on conflict (recipient_id, actor_id, submission_id) where type = 'submission_like'
  do update set created_at = now(), read_at = null;

  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists trg_notify_submission_like on public.mosaic_submission_likes;
create trigger trg_notify_submission_like
  after insert on public.mosaic_submission_likes
  for each row execute function public.notify_submission_like();

-- ── comment on your artwork / reply to your comment ─────────────────────
create or replace function public.notify_submission_comment()
returns trigger as $$
declare
  v_art_author    uuid;
  v_parent_author uuid;
  v_preview       text := left(new.body, 140);
begin
  select author_id into v_art_author
  from public.mosaic_submissions where id = new.submission_id;

  -- the artwork's owner (not for a self-comment)
  if v_art_author is not null and v_art_author <> new.author_id then
    insert into public.notifications (recipient_id, actor_id, type, submission_id, comment_id, preview)
    values (v_art_author, new.author_id, 'submission_comment', new.submission_id, new.id, v_preview);
  end if;

  -- the parent comment's author, on a reply (skip if it's the same person we
  -- just notified above, or the replier themselves)
  if new.parent_id is not null then
    select author_id into v_parent_author
    from public.mosaic_submission_comments where id = new.parent_id;

    if v_parent_author is not null
       and v_parent_author <> new.author_id
       and v_parent_author is distinct from v_art_author then
      insert into public.notifications (recipient_id, actor_id, type, submission_id, comment_id, preview)
      values (v_parent_author, new.author_id, 'submission_reply', new.submission_id, new.id, v_preview);
    end if;
  end if;

  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists trg_notify_submission_comment on public.mosaic_submission_comments;
create trigger trg_notify_submission_comment
  after insert on public.mosaic_submission_comments
  for each row execute function public.notify_submission_comment();

-- ── new follower ───────────────────────────────────────────────────────
-- public.user_saves is now purely user→user follows (saver_id follows
-- saved_id) — the old artwork "save" use was migrated into likes.
create or replace function public.notify_follow()
returns trigger as $$
begin
  if new.saver_id = new.saved_id then
    return new;
  end if;

  insert into public.notifications (recipient_id, actor_id, type)
  values (new.saved_id, new.saver_id, 'follow')
  on conflict (recipient_id, actor_id) where type = 'follow'
  do update set created_at = now(), read_at = null;

  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists trg_notify_follow on public.user_saves;
create trigger trg_notify_follow
  after insert on public.user_saves
  for each row execute function public.notify_follow();

-- ── realtime ───────────────────────────────────────────────────────────
-- Lets the browser subscribe to INSERTs for its own recipient_id so the
-- bell badge updates live. Guarded so re-running this whole file is safe.
do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception
  when duplicate_object then null;
end $$;
