-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- Comments left on an individual artwork (the "cells" rows shown on the
-- artwork detail page in artconnect.html). Replaces text-only "works" —
-- writing/reflections now live here instead of as standalone uploads.

create table if not exists public.cell_comments (
  id          bigint generated by default as identity primary key,
  cell_key    text not null,
  author_id   uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  body        text not null,
  created_at  timestamptz not null default now()
);

create index if not exists cell_comments_cell_key_idx
  on public.cell_comments (cell_key, created_at desc);

alter table public.cell_comments enable row level security;

drop policy if exists "Artwork comments are viewable by everyone" on public.cell_comments;
create policy "Artwork comments are viewable by everyone"
  on public.cell_comments for select
  using (true);

drop policy if exists "Signed-in users can post artwork comments" on public.cell_comments;
create policy "Signed-in users can post artwork comments"
  on public.cell_comments for insert
  with check (auth.uid() = author_id);

-- Either the commenter or the artwork's own author can remove a comment.
drop policy if exists "Author or artwork owner can delete artwork comments" on public.cell_comments;
create policy "Author or artwork owner can delete artwork comments"
  on public.cell_comments for delete
  using (
    auth.uid() = author_id
    or exists (select 1 from public.cells c where c.key = cell_comments.cell_key and c.author_id = auth.uid())
  );

grant select on public.cell_comments to anon, authenticated;
grant insert, delete on public.cell_comments to authenticated;
