-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- Photomosaic feature (weavo.html): admins create a low-res reference image
-- as a grid of target colors; signed-in users upload artwork whose average
-- color gets matched to the closest still-open grid cell, gradually
-- reassembling the reference image out of user submissions.

-- ── 1. Admin flag on profiles ────────────────────────────────────────────
-- SECURITY: profiles currently grants blanket insert/update to `authenticated`
-- with no column restriction, so without locking this down, any signed-in
-- user could run sb.from('profiles').update({ is_admin: true }) and
-- self-promote. Replace the blanket grant with a column-scoped one that
-- excludes is_admin (and id/created_at/updated_at, which are never
-- client-set today).
alter table public.profiles
  add column if not exists is_admin boolean not null default false;

revoke insert, update on public.profiles from authenticated;

grant insert (id, name, avatar_url, username, bio, disabilities, links, country_id, city)
  on public.profiles to authenticated;
grant update (name, avatar_url, username, bio, disabilities, links, country_id, city)
  on public.profiles to authenticated;

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- After running this file, manually promote your own account in the SQL
-- editor (which runs as postgres and bypasses RLS/grants):
--   update public.profiles set is_admin = true where id = '<your-auth-uid>';

-- ── 2. mosaic_projects ───────────────────────────────────────────────────
create table if not exists public.mosaic_projects (
  id                   bigint generated by default as identity primary key,
  title                text not null,
  description          text,
  width                smallint not null,
  height               smallint not null,
  reference_image_url  text not null,
  created_by           uuid not null references auth.users(id) on delete cascade,
  created_at           timestamptz not null default now(),
  constraint mosaic_projects_dims_check
    check (width between 1 and 100 and height between 1 and 100
           and width::integer * height::integer <= 10000)
);

alter table public.mosaic_projects enable row level security;

drop policy if exists "Mosaic projects are viewable by everyone" on public.mosaic_projects;
create policy "Mosaic projects are viewable by everyone"
  on public.mosaic_projects for select
  using (true);

drop policy if exists "Admins can create mosaic projects" on public.mosaic_projects;
create policy "Admins can create mosaic projects"
  on public.mosaic_projects for insert
  with check (
    auth.uid() = created_by
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
  );

drop policy if exists "Admins can update mosaic projects" on public.mosaic_projects;
create policy "Admins can update mosaic projects"
  on public.mosaic_projects for update
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

drop policy if exists "Admins can delete mosaic projects" on public.mosaic_projects;
create policy "Admins can delete mosaic projects"
  on public.mosaic_projects for delete
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

grant select on public.mosaic_projects to anon, authenticated;
grant insert, update, delete on public.mosaic_projects to authenticated; -- gated by RLS above

-- ── 3. mosaic_pixels ─────────────────────────────────────────────────────
-- One row per grid cell, pre-populated when a project is created.
-- submission_id's FK is added after mosaic_submissions exists (circular ref).
create table if not exists public.mosaic_pixels (
  id            bigint generated by default as identity primary key,
  project_id    bigint not null references public.mosaic_projects(id) on delete cascade,
  x             smallint not null,
  y             smallint not null,
  target_r      smallint not null check (target_r between 0 and 255),
  target_g      smallint not null check (target_g between 0 and 255),
  target_b      smallint not null check (target_b between 0 and 255),
  filled        boolean not null default false,
  claimed_by    uuid references auth.users(id) on delete set null,
  claimed_at    timestamptz,
  submission_id bigint,
  constraint mosaic_pixels_project_xy_key unique (project_id, x, y)
);

-- Speeds up "fetch unfilled pixels for project" (the claim-candidate query).
create index if not exists mosaic_pixels_unfilled_idx
  on public.mosaic_pixels (project_id)
  where filled = false;

-- ── 4. mosaic_submissions ────────────────────────────────────────────────
create table if not exists public.mosaic_submissions (
  id           bigint generated by default as identity primary key,
  project_id   bigint not null references public.mosaic_projects(id) on delete cascade,
  pixel_id     bigint not null references public.mosaic_pixels(id) on delete cascade,
  author_id    uuid not null references auth.users(id) on delete cascade,
  author_name  text not null,
  image_url    text not null,
  art_title    text,
  art_description text,
  art_link     text,
  avg_r        smallint not null check (avg_r between 0 and 255),
  avg_g        smallint not null check (avg_g between 0 and 255),
  avg_b        smallint not null check (avg_b between 0 and 255),
  created_at   timestamptz not null default now(),
  constraint mosaic_submissions_art_title_len check (char_length(art_title) <= 80),
  constraint mosaic_submissions_art_description_len check (char_length(art_description) <= 500),
  constraint mosaic_submissions_art_link_len check (char_length(art_link) <= 300)
);

-- Idempotent for installs that already ran this file before these columns existed.
alter table public.mosaic_submissions add column if not exists art_title text;
alter table public.mosaic_submissions add column if not exists art_description text;
alter table public.mosaic_submissions add column if not exists art_link text;

-- One submission per pixel — DB-level backstop on top of the RLS/claim flow.
create unique index if not exists mosaic_submissions_pixel_id_key
  on public.mosaic_submissions (pixel_id);
create index if not exists mosaic_submissions_project_id_idx
  on public.mosaic_submissions (project_id, created_at desc);

alter table public.mosaic_pixels
  add constraint mosaic_pixels_submission_id_fkey
  foreign key (submission_id) references public.mosaic_submissions(id) on delete set null;

alter table public.mosaic_pixels enable row level security;
alter table public.mosaic_submissions enable row level security;

drop policy if exists "Mosaic pixels are viewable by everyone" on public.mosaic_pixels;
create policy "Mosaic pixels are viewable by everyone"
  on public.mosaic_pixels for select
  using (true);

-- Bulk grid creation happens once, admin-only, right after a project is created.
drop policy if exists "Admins can create mosaic pixels" on public.mosaic_pixels;
create policy "Admins can create mosaic pixels"
  on public.mosaic_pixels for insert
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

-- Claim/attach/self-heal state machine for signed-in users. A pixel is only
-- ever touchable here while it's "open" in one of three senses:
--   1. filled = false                                   → anyone may claim it
--   2. filled = true, submission_id null, I claimed it   → I may attach my
--                                                          submission
--   3. filled = true, submission_id null, claim is stale → anyone may sweep
--                                                          it back to open
-- Once filled = true AND submission_id is set, no more updates are allowed
-- here (the row becomes immutable to `authenticated`).
drop policy if exists "Signed-in users can claim and fill mosaic pixels" on public.mosaic_pixels;
create policy "Signed-in users can claim and fill mosaic pixels"
  on public.mosaic_pixels for update
  using (
    filled = false
    or (filled = true and submission_id is null
        and (claimed_by = auth.uid() or claimed_at < now() - interval '10 minutes'))
  )
  with check (
    -- result of phase 1 (claim): I claimed it, nothing attached yet
    (filled = true and claimed_by = auth.uid() and submission_id is null)
    -- result of phase 2 (attach): claimed by me, submission is mine and points at this pixel
    or (filled = true and claimed_by = auth.uid()
        and exists (
          select 1 from public.mosaic_submissions s
          where s.id = submission_id and s.pixel_id = mosaic_pixels.id and s.author_id = auth.uid()
        ))
    -- result of a stale-claim sweep: back to fully open
    or (filled = false and submission_id is null and claimed_by is null)
  );

grant select on public.mosaic_pixels to anon, authenticated;
grant insert on public.mosaic_pixels to authenticated; -- gated to admins by RLS above
grant update (filled, submission_id, claimed_by, claimed_at) on public.mosaic_pixels to authenticated;

drop policy if exists "Mosaic submissions are viewable by everyone" on public.mosaic_submissions;
create policy "Mosaic submissions are viewable by everyone"
  on public.mosaic_submissions for select
  using (true);

-- Only the user who currently holds the claim on a pixel may attach a
-- submission to it, and only once (also enforced by the unique index above).
drop policy if exists "Signed-in users can submit mosaic artwork" on public.mosaic_submissions;
create policy "Signed-in users can submit mosaic artwork"
  on public.mosaic_submissions for insert
  with check (
    auth.uid() = author_id
    and exists (
      select 1 from public.mosaic_pixels px
      where px.id = pixel_id
        and px.project_id = mosaic_submissions.project_id
        and px.filled = true
        and px.submission_id is null
        and px.claimed_by = auth.uid()
    )
  );

grant select on public.mosaic_submissions to anon, authenticated;
grant insert on public.mosaic_submissions to authenticated;

-- ── 5. moderation & self-service deletion ────────────────────────────────
-- Lets an author remove their own submitted artwork, or an admin remove
-- anyone's (weavo.html's lightbox "Delete" button). Cascades to that piece's
-- likes/saves/comments automatically via the existing FK "on delete cascade"
-- constraints, and its mosaic_pixels row's submission_id is set null by
-- "on delete set null" above. The pixel itself is then reset back to fully
-- open by a client-side update (weavo.html's deleteWeavoSubmission) — no
-- extra pixels policy needed for the author's own case, since "Signed-in
-- users can claim and fill mosaic pixels" above already permits resetting a
-- pixel you're still the claimant of.
drop policy if exists "Admins can delete mosaic submissions" on public.mosaic_submissions;
drop policy if exists "Author or admin can delete mosaic submissions" on public.mosaic_submissions;
create policy "Author or admin can delete mosaic submissions"
  on public.mosaic_submissions for delete
  using (
    auth.uid() = author_id
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
  );

grant delete on public.mosaic_submissions to authenticated; -- gated by RLS above

-- After deleting a submission, the client also resets its now-orphaned
-- pixel back to fully open (rather than waiting up to 10 minutes for the
-- stale-claim sweep). The existing "claim and fill" update policy only
-- covers a pixel's own claimant or a claim that's already gone stale, so
-- admins need their own broader update policy to do that reset immediately.
drop policy if exists "Admins can manage mosaic pixels" on public.mosaic_pixels;
create policy "Admins can manage mosaic pixels"
  on public.mosaic_pixels for update
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));
