-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- Run AFTER supabase_mosaic_pieces.sql (this reads new.parent_id) and
-- supabase_site_settings.sql (the upload limit is a site option).
--
-- Moderation tools for the admin page (/{lang}/admin): the Comments tab, the
-- append-only action log behind every bulk deletion, a per-account upload
-- block, and an upload rate limit that is finally configurable instead of
-- hardcoded. Also lets admins remove the actual Storage files behind an
-- artwork — until now deleting an artwork left its uploaded image in the
-- `artwork` bucket, still reachable by its public URL, which is exactly the
-- wrong outcome when the reason for deleting it was the image itself.
--
-- CLAUDE.md §13 (no bulk artwork deletion) still holds at the database:
-- there is deliberately NO "delete many submissions" RPC or policy here.
-- The admin page's multi-select deletes rows ONE AT A TIME through the
-- existing per-row delete policy, capped at 20 per action in the client.
-- (User decision 2026-09-11 — recorded in CLAUDE.md §13.)

-- ── 1. admins can delete any comment ─────────────────────────────────────
-- Until now only the comment's author or the artwork's author could, so an
-- admin looking at a reported comment had no way to act on it.
drop policy if exists "Author or artwork owner can delete mosaic comments" on public.mosaic_submission_comments;
drop policy if exists "Author, artwork owner or admin can delete mosaic comments" on public.mosaic_submission_comments;
create policy "Author, artwork owner or admin can delete mosaic comments"
  on public.mosaic_submission_comments for delete
  using (
    auth.uid() = author_id
    or exists (
      select 1 from public.mosaic_submissions s
      where s.id = mosaic_submission_comments.submission_id and s.author_id = auth.uid()
    )
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
  );

-- ── 2. admin action log (append-only) ────────────────────────────────────
-- Every deletion an admin makes from the admin page writes one row here, so
-- a mistake can be traced back to who did it and when. There is no delete
-- or update grant: the log can be read (admins only) and appended to (only
-- through the RPC below, which stamps the actor itself), never rewritten.
create table if not exists public.admin_audit_log (
  id          bigint generated by default as identity primary key,
  actor_id    uuid references auth.users(id) on delete set null,
  actor_name  text,
  action      text not null,
  target_type text not null,
  target_id   text,
  detail      jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  constraint admin_audit_log_action_len check (char_length(action) <= 40),
  constraint admin_audit_log_target_type_len check (char_length(target_type) <= 40)
);

-- Nullable actor_id keeps old entries readable after an account is gone.
alter table public.admin_audit_log alter column actor_id drop not null;

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log (created_at desc, id desc);

alter table public.admin_audit_log enable row level security;

drop policy if exists "Admins can read the audit log" on public.admin_audit_log;
create policy "Admins can read the audit log"
  on public.admin_audit_log for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

-- Supabase grants ALL on newly created public tables to anon and
-- authenticated by default; revoke first so the grant below is the whole
-- story. RLS already hides every row from non-admins, but an audit trail
-- that cannot be rewritten is the point of having one.
revoke all on public.admin_audit_log from anon, authenticated;
grant select on public.admin_audit_log to authenticated;
-- No insert/update/delete grant on purpose — writes go through the RPC.

-- Records one action. security definer so it can write to a table nobody
-- has an insert grant on; the actor is taken from auth.uid(), never from
-- the caller's arguments, so an entry cannot be attributed to someone else.
create or replace function public.admin_log_action(
  p_action      text,
  p_target_type text,
  p_target_id   text default null,
  p_detail      jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_id bigint;
begin
  if not exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin) then
    raise exception 'admin only';
  end if;

  insert into public.admin_audit_log (actor_id, actor_name, action, target_type, target_id, detail)
  values (
    auth.uid(),
    (select coalesce(username, name) from public.profiles where id = auth.uid()),
    left(coalesce(p_action, ''), 40),
    left(coalesce(p_target_type, ''), 40),
    left(p_target_id, 200),
    coalesce(p_detail, '{}'::jsonb)
  )
  returning id into v_id;

  return v_id;
end;
$fn$;

grant execute on function public.admin_log_action(text, text, text, jsonb) to authenticated;

-- ── 3. per-account upload block ──────────────────────────────────────────
-- Deleting a spam flood is pointless if the same account can immediately
-- upload it again. The column is NOT in the column-scoped grants of
-- supabase_mosaic.sql §1, so a client cannot set it on itself — it only
-- changes through the admin RPC below.
alter table public.profiles
  add column if not exists upload_blocked boolean not null default false;

create or replace function public.admin_set_upload_blocked(p_user uuid, p_blocked boolean)
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_blocked boolean := coalesce(p_blocked, false);
begin
  if not exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin) then
    raise exception 'admin only';
  end if;
  if p_user is null then
    raise exception 'user id required';
  end if;

  update public.profiles set upload_blocked = v_blocked where id = p_user;

  perform public.admin_log_action(
    case when v_blocked then 'upload_block' else 'upload_unblock' end,
    'profile',
    p_user::text,
    jsonb_build_object('username', (select coalesce(username, name) from public.profiles where id = p_user))
  );

  return v_blocked;
end;
$fn$;

grant execute on function public.admin_set_upload_blocked(uuid, boolean) to authenticated;

-- ── 4. upload rate limit — now a site option, and block-aware ────────────
-- Supersedes the copies in supabase_mosaic_submissions_rate_limit.sql (which
-- created the trigger this replaces the body of) and supabase_mosaic_pieces.sql
-- §3 (which added the "pieces are not uploads" skip). Both hardcoded 20 per
-- 10 minutes; CLAUDE.md §16 says every knob belongs in the admin page, so the
-- numbers now come from site_settings (uploadLimitCount / uploadLimitMinutes,
-- defaults 20 and 10 in js/common.js SITE_SETTING_DEFAULTS).
-- NOTE: re-running either of those two older files would put the hardcoded
-- version back. Re-run this file afterwards if that ever happens.
create or replace function public.enforce_mosaic_submission_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_minutes int;
  v_max     int;
  v_recent  int;
begin
  -- 49 piece rows arrive with every upload; only the artwork rows count.
  if new.parent_id is not null then
    return new;
  end if;

  if exists (select 1 from public.profiles p where p.id = new.author_id and p.upload_blocked) then
    raise exception 'uploads are blocked for this account'
      using errcode = 'RATE2';
  end if;

  -- Clamped to the same range as the admin sliders so a bad stored value
  -- can never disable the limit outright.
  select least(500, greatest(1, coalesce(
    (select (settings->>'uploadLimitCount')::int from public.site_settings where id = true), 20)))
    into v_max;
  select least(1440, greatest(1, coalesce(
    (select (settings->>'uploadLimitMinutes')::int from public.site_settings where id = true), 10)))
    into v_minutes;

  select count(*) into v_recent
  from public.mosaic_submissions
  where author_id = new.author_id
    and parent_id is null
    and created_at > now() - make_interval(mins => v_minutes);

  if v_recent >= v_max then
    raise exception 'upload rate limit exceeded — please wait a few minutes and try again'
      using errcode = 'RATE1';
  end if;

  return new;
end;
$fn$;

-- The trigger itself already exists (supabase_mosaic_submissions_rate_limit.sql);
-- recreated here so this file also works on an install that never ran it.
drop trigger if exists mosaic_submissions_rate_limit on public.mosaic_submissions;
create trigger mosaic_submissions_rate_limit
  before insert on public.mosaic_submissions
  for each row execute function public.enforce_mosaic_submission_rate_limit();

-- ── 5. Storage: admins can remove any artwork file ───────────────────────
-- Additive to the per-user prefix policies in
-- supabase_delete_account_storage.sql. Without these an admin deleting
-- someone else's artwork leaves the image file live in the bucket.
drop policy if exists "Admins can list all artwork files" on storage.objects;
create policy "Admins can list all artwork files"
  on storage.objects for select
  using (
    bucket_id = 'artwork'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
  );

drop policy if exists "Admins can delete any artwork file" on storage.objects;
create policy "Admins can delete any artwork file"
  on storage.objects for delete
  using (
    bucket_id = 'artwork'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
  );
