// Generated by tools/sky-scene.js — do not edit by hand.
// The moving layers of the sky page's photograph: where each sits, in the
// photograph's own pixels ([x, y, width, height] of SKY_W × SKY_H in
// js/sky-figures.js), and the stars that twinkle ([x, y, size]).
// No DOM. Read by js/stars.js.
const SKY_BARE_IMAGE = '/sky/night-bare.webp?v=20260927';
const SKY_SCENE = {
  trees: [
    { key: 'left', src: '/sky/trees-left.webp?v=20260927', box: [0, 581, 300, 240] },
    { key: 'mid', src: '/sky/trees-mid.webp?v=20260927', box: [300, 728, 561, 93] },
    { key: 'right', src: '/sky/trees-right.webp?v=20260927', box: [1446, 718, 470, 103] },
  ],
  glint: { src: '/sky/sea-glint.webp?v=20260927', box: [174, 757, 1731, 64] },
  ripples: [
    { src: '/sky/sea-ripple-a.webp?v=20260927', box: [174, 738, 1731, 83] },
    { src: '/sky/sea-ripple-b.webp?v=20260927', box: [174, 738, 1731, 83] },
  ],
};
const SKY_TWINKLES = [[15,114,7.7],[202,338,5.6],[249,476,6],[284,171,5.6],[368,479,6],[414,50,5.8],[429,276,5.8],[495,340,5.5],[496,98,5.6],[520,529,6.4],[641,58,5.9],[725,516,7.2],[760,322,6.2],[872,466,9.2],[888,47,5.6],[936,361,7.2],[1015,363,9.5],[1068,151,6.7],[1138,309,9.5],[1139,383,6.7],[1270,133,7.1],[1300,248,8.5],[1350,187,9.5],[1430,496,5.5],[1473,200,6.1],[1519,431,5.2],[1575,66,7.9],[1644,224,5.2],[1651,37,7.3],[1711,380,6.2],[1771,133,6.1],[1859,317,6.1]];
