-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- Comments (with one level of replies) on individual mosaic artwork
-- submissions (weavo.html). Mirrors public.cell_comments / profile_comments
-- but adds parent_id for threading.

-- Snapshotted at submission time, same rationale as the existing author_name
-- column: lets the lightbox render a clickable avatar next to an artwork's
-- byline without an extra join back to profiles on every load.
alter table public.mosaic_submissions
  add column if not exists author_avatar_url text;

create table if not exists public.mosaic_submission_comments (
  id                bigint generated by default as identity primary key,
  submission_id     bigint not null references public.mosaic_submissions(id) on delete cascade,
  parent_id         bigint references public.mosaic_submission_comments(id) on delete cascade,
  author_id         uuid not null references auth.users(id) on delete cascade,
  author_name       text not null,
  author_avatar_url text,
  body              text not null,
  created_at        timestamptz not null default now(),
  constraint mosaic_submission_comments_body_len check (char_length(body) between 1 and 1000)
);

create index if not exists mosaic_submission_comments_submission_id_idx
  on public.mosaic_submission_comments (submission_id, created_at);
create index if not exists mosaic_submission_comments_parent_id_idx
  on public.mosaic_submission_comments (parent_id);

alter table public.mosaic_submission_comments enable row level security;

drop policy if exists "Mosaic comments are viewable by everyone" on public.mosaic_submission_comments;
create policy "Mosaic comments are viewable by everyone"
  on public.mosaic_submission_comments for select
  using (true);

-- Kept deliberately simple (just the author check) — a correlated subquery
-- here checking "a reply's parent belongs to the same submission" turned
-- out to be unreliable under RLS (rejected valid inserts with a bare
-- "violates row-level security policy" error and no useful detail). That
-- cross-row integrity check now lives in a BEFORE INSERT trigger below,
-- which is the right tool for validating against other rows anyway.
drop policy if exists "Signed-in users can post mosaic comments" on public.mosaic_submission_comments;
create policy "Signed-in users can post mosaic comments"
  on public.mosaic_submission_comments for insert
  with check (auth.uid() = author_id);

create or replace function public.check_mosaic_comment_parent()
returns trigger as $$
begin
  if new.parent_id is not null and not exists (
    select 1 from public.mosaic_submission_comments p
    where p.id = new.parent_id and p.submission_id = new.submission_id
  ) then
    raise exception 'parent comment must belong to the same submission';
  end if;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists trg_mosaic_comment_parent_check on public.mosaic_submission_comments;
create trigger trg_mosaic_comment_parent_check
  before insert on public.mosaic_submission_comments
  for each row execute function public.check_mosaic_comment_parent();

-- Either the commenter or the artwork's own author can remove a comment.
drop policy if exists "Author or artwork owner can delete mosaic comments" on public.mosaic_submission_comments;
create policy "Author or artwork owner can delete mosaic comments"
  on public.mosaic_submission_comments for delete
  using (
    auth.uid() = author_id
    or exists (
      select 1 from public.mosaic_submissions s
      where s.id = mosaic_submission_comments.submission_id and s.author_id = auth.uid()
    )
  );

grant select on public.mosaic_submission_comments to anon, authenticated;
grant insert, delete on public.mosaic_submission_comments to authenticated;
