-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- Adds a profiles table for the Users tab. Designed to be extended later
-- with more signup fields (just add columns — the app reads by name).

create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Profile fields users fill in themselves (separate from the Google name/avatar,
-- which are set automatically on sign-in).
alter table public.profiles
  add column if not exists username        text,
  add column if not exists bio             text,
  add column if not exists neurodivergence text[] not null default '{}',
  add column if not exists links           jsonb not null default '{}'::jsonb;

-- Case-insensitive unique usernames; null allowed until a user sets one.
create unique index if not exists profiles_username_key
  on public.profiles (lower(username))
  where username is not null;

alter table public.profiles enable row level security;

drop policy if exists "Profiles are viewable by everyone" on public.profiles;
create policy "Profiles are viewable by everyone"
  on public.profiles for select
  using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- RLS policies only take effect once the role has table-level privileges too —
-- without this grant, guest (anon) requests get a permission error before the
-- "viewable by everyone" policy is ever evaluated, so the Users tab looks empty.
grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;

-- Keeps updated_at current on edits.
create or replace function public.set_profiles_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_profiles_updated_at();

-- Per-user approved-piece counts, used by the Users tab. Recomputed live
-- from `cells`, so it never drifts out of sync.
create or replace view public.profile_counts as
select author_id as id, count(*) as piece_count
from public.cells
where approved = true
group by author_id;

grant select on public.profile_counts to anon, authenticated;

-- Guestbook-style comments left on a user's profile page.
create table if not exists public.profile_comments (
  id          bigint generated by default as identity primary key,
  profile_id  uuid not null references public.profiles(id) on delete cascade,
  author_id   uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  body        text not null,
  created_at  timestamptz not null default now()
);

create index if not exists profile_comments_profile_id_idx
  on public.profile_comments (profile_id, created_at desc);

alter table public.profile_comments enable row level security;

drop policy if exists "Profile comments are viewable by everyone" on public.profile_comments;
create policy "Profile comments are viewable by everyone"
  on public.profile_comments for select
  using (true);

drop policy if exists "Signed-in users can post profile comments" on public.profile_comments;
create policy "Signed-in users can post profile comments"
  on public.profile_comments for insert
  with check (auth.uid() = author_id);

-- Either the commenter or the profile owner can remove a comment.
drop policy if exists "Author or profile owner can delete profile comments" on public.profile_comments;
create policy "Author or profile owner can delete profile comments"
  on public.profile_comments for delete
  using (auth.uid() = author_id or auth.uid() = profile_id);

grant select on public.profile_comments to anon, authenticated;
grant insert, delete on public.profile_comments to authenticated;
